export const componentNames = [
    "Label",
    "Header",
    "Toolbar",
    "LoginView",
    "Table",
    "SideNav",
    "Button",
    "Alert",
    "List",
    "Card",
    "List",
    "Spinner",
    "Progress",
    "BreadCrum",
    "SpeedDial",
    "Video",
    "TextField",
    "Image",
    "Collapse",
    "PieChart",
    "DatePicker",
    "Form",
    "DeviceMockUp"
    // Add more component names as needed
];
